### ISSUE TITLE
Optimize for GIFs

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-module-tnd-imgix#2]
**Note that currently GIFs are only enabled for ndbooks.com** 

Since Gifs are an edge case, if we make changes I'd prefer it not be one that could impact build times. 

Sourced from: https://github.com/theNewDynamic/ndbooks.com/issues/162

Gifs solved by Imgix, but we may need to make some adjustments. 

> Anyways, I've enabled GIFs for your source. It'll take 10-15 minutes for them to re-deploy, but your GIFs should work after that- if they don't, you can use our purge tool to clear the GIFs from our cache, which will fix the issue.

> Before you start using GIFs, it's important that you read the information below. Since GIFs are much larger than standard images and can have a much larger impact on your billing overall, I wanted to give you a little more info to ensure the success of the GIFs. The most important thing to do is use auto=format,compress for the animated GIFs. It will actually turn those GIFs into an animated WebP in supported browsers (such as Chrome).

> We do not recommend the transformation of extremely large GIFs, extremely long GIFs, or any upscaling of GIFs. Transforming long or heavy GIFs is an extremely time-intensive process that can cause your image rendering to drastically slow down.

> Every other parameter is the same except for the quality parameter. Since GIFs operate in such a different way from images, we created a new parameter called gif-q. I would suggest gif-q=35 to gif-q=60. The higher the number, the more compression applied to the GIF.

> Just to show you the difference:

> This one is 624 KB in Chrome: http://tom.imgix.net/dogmilk.gif?frame=60-130&w=300&h=200&auto=format,compress&gif-q=35

> This one without those parameters is 1.7 MB: http://tom.imgix.net/dogmilk.gif?frame=60-130&w=300&h=200

> Also, if you wanted to make a larger change (but certainly would require more front end work) you could convert the GIF to an MP4 and use some video tags to make it look like a GIF (<video preload="auto" autoplay="autoplay" muted="muted" loop="loop" style="width: 300px; height: 169px;">). You will see drastic performance changes using this option. If you want to know more about the fm=mp4 idea, just let me know!

> Here is a CodePen example of what I am talking about: https://codepen.io/daletom/pen/EQoazB

> For more information regarding GIF parameters, you can read through our documentation below:
https://docs.imgix.com/apis/url/animation

> One final note - It's best to not compress your GIFs before serving them with imgix. Since we optimize images, uploading a pre-compressed GIF can have the opposite effect, which can degrade the quality and increase the GIF's file size.

**Comment by regisphilibert** [comment]
I'm not sure I see what is the spec here? 
What can the module do to help the gif implementation?

We could decide to enforce a `gif-q=60` transformation for every image with a `.gif` extension as we are not controling which image expansion are used in the templates. (mostly added through CMS)
